services:
  discord-bot:
    build: ./discord-bot
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
  puppeteer:
    build: ./puppeteer
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: redis:latest
    # volumes:
    #   - ./data:/data
    restart: unless-stopped
# volumes:
#   redis-data:
