services:
  # discord-bot:
  #   build: ./discord-bot
  #   env_file:
  #     - .env
  puppeteer:
    build: ./puppeteer
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN
    security_opt: 
      - seccomp=unconfined
    depends_on:
      - redis
  redis:
    image: redis:latest
    volumes:
      - ./redis-data:/data

volumes:
  redis-data:
