services:
  discord-bot:
    build: ./discord-bot
    env_file:
      - .env
    depends_on:
      - redis
  puppeteer:
    build: ./puppeteer
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    depends_on:
      - redis
  redis:
    image: redis:latest
    volumes:
      - ./data:/data

volumes:
  redis-data:
